### PR TITLE
Mention Highcharts JS as a pre-requisite in docs.

### PR DESCRIPTION
**Pull request by arvindsv**
Highcharts now needs to be provided externally.

### CODE REVIEW

**Comment by arvindsv** [comment]
@maheshp We say `PostgreSQL 9.6` is needed in one place in the docs and `9.6 and later` in another. We should clarify that.

**Comment by arvindsv** [comment]
@kritika-singh3 took a look.

**Comment by maheshp** [comment]
> @maheshp We say PostgreSQL 9.6 is needed in one place in the docs and 9.6 and later in another. We should clarify that.

@arvindsv while I believe the plugin should work with latest versions of PostgreSQL, but this is something we haven't tested. Hence, we should just mention `PostgreSQL 9.6` everywhere for now.

**Comment by arvindsv** [comment]
@maheshp Ok. I've updated it in: https://github.com/gocd/gocd-analytics-plugin/commit/5e8f53a02ba02a2f92a81b03f968a9fa4a0ff59a

**Pull request merged**
